# Generated by Django 4.2.26 on 2026-01-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_merge_0002_notes_likes_0002_notes_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
